FROM golang:1.18.1

WORKDIR /workspace

COPY go.mod ./
COPY go.sum ./
 
ENV GOPATH /go
ENV GOBIN /go/bin

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV SHELL /bin/zsh

RUN apt update && apt install -y git zsh vim fzf locales gcc musl-dev curl iputils-ping telnet graphviz bc jq && rm -rf /var/lib/apt/lists/*
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
COPY .devcontainer/.zshrc /root/.zshrc

RUN go install -v golang.org/x/tools/gopls@v0.8.3
RUN go install -v github.com/rogpeppe/godef@v1.1.2
RUN go install -v github.com/rakyll/gotest@v0.0.6
RUN go install -v github.com/ramya-rao-a/go-outline@1.0.0
RUN go install -v github.com/go-delve/delve/cmd/dlv@v1.8.1
RUN go install -v golang.org/x/perf/cmd/benchstat@v0.0.0-20221222172245-91a04616dc65
RUN go mod download

CMD [ "zsh" ]